### ISSUE TITLE
Not converging solution and LinalgError: Matrix is singular to machine precision

### ISSUE THREAD

**Issue by twparzi4** [bkelly-lab/ipca#26]
I encountered these two issues when I was trying to apply IPCA model to a stock market index option, following the pattern in Büchner M, Kelly B(2022). To be specific, I construct 15 features as it was in the paper. However, when I was fitting the IPCA model, it never converged when number of factors in this model is larger than 1. In fact, the aggregate update in every step tends to go up and explore for these multi-factors situation. For reference, my feature dataset looks like this:
<img width="1195" alt="image" src="https://github.com/bkelly-lab/ipca/assets/162603062/b056e093-3f89-4ea1-af7a-57eff36fafe6">
The last eight columns are Greeks interacted with a 0-1 variable indicating put options. And the features are re-scaled into [-0.5,0.5].

Next, as I was fitting the IPCA model with characteristic managed portfolio, not only that it did not converge, but also that there was a error raised saying: _LinAlgError: Matrix is singular to machine precision._
As I looked into the source code where this error is raised, I found that it was that a singular matrix was passed into function _Ft_fit_portfolio during ALS process. 
`Traceback (most recent call last):

  File "C:\code.py", line 345, in <module>
    analyzer.run()

  File "C:\code.py", line 298, in run
    rgsr = self.IPCA(K, False, 'portfolio', quiet=False)

  File "C:\code.py", line 235, in IPCA
    rgsr = rgsr.fit(X=self.features, y=self.label, data_type=datatype, **kwargs)

  File "D:\ana\lib\site-packages\ipca\ipca.py", line 221, in fit
    Gamma, Factors = self._fit_ipca(X=X, y=y, indices=indices, Q=Q,

  File "D:\ana\lib\site-packages\ipca\ipca.py", line 1013, in _fit_ipca
    Gamma_New, Factor_New = ALS_fit(Gamma_Old, *ALS_inputs,

  File "D:\ana\lib\site-packages\ipca\ipca.py", line 1074, in _ALS_fit_portfolio
    F_New[:,t] = _Ft_fit_portfolio(Gamma_Old, W[:,:,t],

  File "D:\ana\lib\site-packages\ipca\ipca.py", line 1449, in _Ft_fit_portfolio
    return np.squeeze(_numba_solve(m1, m2.reshape((-1, 1))))

  File "D:\ana\lib\site-packages\numba\np\linalg.py", line 899, in _inv_err_handler
    raise np.linalg.LinAlgError(

LinAlgError: Matrix is singular to machine precision.`

Combining these two issues, I think that it was something wrong numerically(or statistically) in my features data, but I have no clue where exactly goes wrong and how I can fix this problem and let my code work. Additionally, I have seen issue on the same LinAlgError raised before, however, I guess that was a different situation to my problem since there's no columns with all entries being 0. 

Please tell me how I can fix this issue, And any hint or suggestion is welcomed as well.

**Comment by avifin19** [comment]
Hi, set the alpha to non-zero values ( something like 1e-10) when setting the restricted/unrestricted model. This should help avoid the singular matrix error by introducing regularization. However , please note that this will slowdown the code. Additionally, check if your features have multi-collinearity issues.

**Comment by twparzi4** [comment]
This is a really helpful advice.  Many thanks!
